version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: weather_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  pgadmin:
    image: dpage/pgadmin4
    container_name: weather_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  airflow:
    build: .
    container_name: weather_airflow
    restart: always
    depends_on:
      - postgres
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      # Bddel weather_db b airflow_db hna:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/airflow_db
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__FERNET_KEY=${AIRFLOW_FERNET_KEY}
    volumes:
      - ./dags:/app/dags
      - ./src:/app/src
      - ./data:/app/data
    ports:
      - "${AIRFLOW_PORT}:8080"
    command: bash -c "airflow db init && airflow users create --username ${AIRFLOW_USER} --firstname ${AIRFLOW_FIRSTNAME} --lastname ${AIRFLOW_LASTNAME} --role Admin --email ${AIRFLOW_EMAIL} --password ${AIRFLOW_PASSWORD} && airflow standalone"
  streamlit:
    build: .
    container_name: weather_streamlit
    restart: always
    depends_on:
      - postgres
    ports:
      - "${STREAMLIT_PORT}:8501"
    volumes:
      - ./dashboard:/app/dashboard
      - ./src:/app/src
    command: streamlit run dashboard/app.py --server.port=8501 --server.address=0.0.0.0

volumes:
  postgres_data: